#include "/Engine/Public/Platform.ush"
#if SM6_PROFILE
#include "/Engine/Private/Common.ush"

// GaussianSplatData type
#include "GaussianSplatTypes.ush"
#include "GaussianSplatConstants.ush"
#include "GaussianSplatCommon.ush"

#include "Quaternion.ush"

#define MAX_SPLATS_IN_TILE (65536)

///////////////////////
// DATA FROM PREVIOUS STAGE
uint SplatCount;
uint NumTileConjugateSplat;
StructuredBuffer<SplatViewData> TheSplatViewData; // naming is so strict

///////////////////////
// TILE DATA
StructuredBuffer<uint2> TileToSplatRanges;         // Size = (TileCountX * TileCountY), range of splats idx

///////////////////////
// IO DATA
//RWStructuredBuffer<uint> OutColourR8G8B8A8Buffer;      // output color map with R8G8B8A8 format for CPU
//RWStructuredBuffer<float> OutDepthF32Buffer;           // output depth map with Float32 format for CPU
RWTexture2D<float4> OutputColourTexture;               // output GPU colour texture
RWTexture2D<float> OutputDepthTexture;                 // output GPU depth texture
uint2 OutputTextureSize;
float4 DepthOutputThreshold; // x = enable depth write, w = alpha cutout threshold

// From above to follows, using SortGPUBuffers() on CPU
StructuredBuffer<uint> TileConjugateSplatValuesSorted; // value = splat_index(index of TheSplatViewData), sorted


///////////////////////
// COMMON DATA
float4 VecScreenParams;

// Dispatch 1. See InclusiveSum.usf


// Dispatch 3
// UNREAL GPU SORTING DOES NOT SUPPORT 64BIT KEYS
// BUT TRY SQUEEZING (TILE_ID|DEPTH) INTO 32BIT FIRST


// Assume inst_id < NumTileConjugateSplat, this is the main interface to retrieve sorted SplatView index
uint GetSortedSplatViewIndex(uint inst_id)
{
    return TileConjugateSplatValuesSorted[inst_id];

}


///////////////////////
// GROUP SHARED MEMORY
// From MS: Groupshared memory is limited to 16KB per group. A single thread is limited to 256 byte region of groupshared memory for writing.
// But from reaity the compiler gives error: Total Thread Group Shared Memory storage is 45056, exceeded 32768. <- which means SM6 has 32K group shared memory limit
// Also from MS: A Compute Shader thread may only write to its own region of TGSM. This write-only region has a maximum size of 256 bytes or less, with the maximum decreasing as the number of threads declared for the group increases.
/*
Number of Threads in Group	Maximum TGSM Size Per Thread
0-64                        256
65-68                       240
69-72                       224
73-76                       208
77-84                       192
85-92                       176
93-100                      160
101-112                     144
113-128                     128
129-144                     112
145-168                     96
169-204                     80
205-256                     64
257-340                     48
341-512                     32
513-768                     16
*/

groupshared int collected_id[COLLECTOR_BATCH_SIZE];
groupshared float2 collected_xy[COLLECTOR_BATCH_SIZE];
groupshared float4 collected_conic_opacity[COLLECTOR_BATCH_SIZE];
groupshared float4 collected_rgbz[COLLECTOR_BATCH_SIZE]; // RGB + clipZ

// Dispatch 5
// Each thread is a pixel
// Each thread group is a tile
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void CSRenderViewData(uint3 groupID : SV_GroupID,
            uint3 threadIDInGroup : SV_GroupThreadID,
            uint3 dispatchThreadID : SV_DispatchThreadID)
{
 
    uint2 localPos = threadIDInGroup.xy;
    //uint2 globalPos = uint2(
        //groupID.x * TILE_SIZE + localPos.x,
        //groupID.y * TILE_SIZE + localPos.y); // Or just use dispatchThreadID.xy
    uint2 globalPos = dispatchThreadID.xy;
    
    // TODO: precompute
    uint W = (uint) VecScreenParams.x;
    uint H = (uint) VecScreenParams.y;
    uint horizontal_block_count = (W + TILE_SIZE - 1) / TILE_SIZE; // RoundUp(W / TileSize)
    
    uint2 pix = globalPos;
    if (pix.x >= OutputTextureSize.x || pix.y >= OutputTextureSize.y)
        return;
    
    float2 pixf = float2(pix.x, pix.y);
    uint pix_id = W * pix.y + pix.x;
    
    // out of bounds check
    bool inside = pix.x < W && pix.y < H;
    bool done = !inside;
    
    // Load start/end range of IDs to process in bit sorted list.
    uint flattenGroupId = groupID.y * horizontal_block_count + groupID.x;
    // Ranges.length = numTileX * numTileY = totalTileCount = totalGroupCount
    // .xy contains splatIdx. range.x = lower bound splatIdx(inclusive), range.y = upper bound splatIdx (exclusive)
    // fetch sorted splats index range     
    uint2 splatRange = TileToSplatRanges[flattenGroupId];
    int splatIndexStart = (int)splatRange.x;
    int splatIndexEnd = (int)splatRange.y; // exclusive
    int remainedSplats = clamp(splatIndexEnd - splatIndexStart, 0, MAX_SPLATS_IN_TILE);
    
    // Use groupshared memory in Compute shader, to mimic cooperative groups in CUDA
    // the num of splats in each batch must be equal or smaller than COLLECTOR_BATCH_SIZE
    const int numBatches = ((splatIndexEnd - splatIndexStart + COLLECTOR_BATCH_SIZE - 1) / COLLECTOR_BATCH_SIZE); // the num of rounds can be arbitrary actually, doesn't have to be associated with BLOCK_SIZE. but the original implementation seems use COLLECTOR_BATCH_SIZE=BLOCK_SIZE as granularity
    
    // Initialize helper variables
    float T = 1.0f;
    float3 C = float3(0, 0, 0);
    float topZ = 0;
    
    uint flattenLocalThreadId = threadIDInGroup.y * TILE_SIZE + threadIDInGroup.x; // block.thread_rank()
    
    // Iterate over batches until all done or range is complete
    for (int i = 0; i < numBatches; i++)
    {
        // Collectively fetch per-Gaussian data from global to shared
        int progress = i * COLLECTOR_BATCH_SIZE + flattenLocalThreadId;
        bool groupSharedMemoryFilled = false;
        uint tileConjSplatIdx = splatIndexStart + progress;
        if (tileConjSplatIdx < splatIndexEnd && tileConjSplatIdx < NumTileConjugateSplat)
        {
            uint coll_id = GetSortedSplatViewIndex(tileConjSplatIdx); // splat index
            if (coll_id < SplatCount)
            {
                collected_id[flattenLocalThreadId] = coll_id;
                
                SplatViewData splatView = TheSplatViewData[coll_id];
                collected_xy[flattenLocalThreadId] = splatView.mean_xy;
                collected_conic_opacity[flattenLocalThreadId] = splatView.conic;
                collected_rgbz[flattenLocalThreadId] = float4(splatView.diffuse_opacity.rgb, splatView.radii_clipz.y);
                    
                groupSharedMemoryFilled = true;
            }
        }
        
        if (!groupSharedMemoryFilled)
        {
            collected_id[flattenLocalThreadId] = -1; // this is where the batch index is out of bounds, invalid sorting result, etc etc
            collected_xy[flattenLocalThreadId] = float2(0, 0);
            collected_conic_opacity[flattenLocalThreadId] = float4(0, 0, 0, 0);
            collected_rgbz[flattenLocalThreadId] = float4(0, 0, 0, 0);
        }

        
        // Make sure the collected_* arrays are valid
        GroupMemoryBarrierWithGroupSync(); // block.sync();
        
        // Doing each batch, iterate over collectged splats
        //for (int j = 0; !done && j < min(COLLECTOR_BATCH_SIZE, remainedSplats); j++)
        // It seems removing the test of "done" improves a lot of stability
        const int actualRemainedSplats = min(COLLECTOR_BATCH_SIZE, remainedSplats);
        for (int j = 0; j < actualRemainedSplats; j++)
        {
            int splatIdx = collected_id[j];
            if (splatIdx < 0) // only test for -1, as the SplatCount boundary check has been done in the collection phase
                continue;
            
            float2 mean = collected_xy[j]; // somehow need to access the splat to get mean
            float4 con_o = collected_conic_opacity[j];
            float alpha;
            bool alphaValid = CalcAlpha(con_o, mean, pixf, alpha);
            
            if (!alphaValid)
                continue;
            
            float test_T = T * (1 - alpha);
            if (test_T < 0.0001f)
            {
                done = true;
                continue;
            }
            
            topZ = max(topZ, clamp(collected_rgbz[j].w, 0.0, 1.0));
            
            // Eq. (3) from 3D Gaussian splatting paper.
            // features: calculated splat color buffer from previous stage
            C += collected_rgbz[j].rgb * alpha * T;
            
            T = test_T;
        }
        
        remainedSplats -= COLLECTOR_BATCH_SIZE;
        
        // Make sure all the GPU threads are finished with using group shared memory, as in next loop group shared memories will be re-written
        GroupMemoryBarrierWithGroupSync();
        
        // Adding this break seems improve stability
        if (remainedSplats <= 0)
            break;
    }
    
    // All threads that treat valid pixel write out their final
	// rendering data to the frame and auxiliary buffers.
    if (inside)
    {
        float3 colourRGB = C;

        uint2 texPixel = uint2(pix.x, H - 1 - pix.y); // this will output image on the top left corner, easier for composite to sample

        
        float alpha = (1.0 - T);
        // sRGB is a gamma-encoded color space (approx gamma 2.2). To convert from linear to sRGB, Unreal applies a gamma correction, roughly
        // sRGB = pow(linear, 1/2.2)
        // So usually Unreal expect an input of linear colour so that the gamma correction to sRGB goes as it expected.
        // Our stuff is always in sRGB.
        // But depending on which stage to inject the image, you will need to either apply the inverse gamma correction UnrealSRGBToLinear(c), or leave it alone
        // So if it's after tone mapping(ToneMapping, FXAA), you should remove the term
        
            
        // Write to OutputDepthTexture based on clip space depth calculated in preprocess stage
        // Trick depth with alpha value to "soften" the edge usually won't do better
        if (DepthOutputThreshold.x > 0) // check if depth write is on
        {
            // do depth threshold
            if (alpha > DepthOutputThreshold.w)
            {
                OutputColourTexture[texPixel] = float4(clamp(colourRGB / alpha, 0.0, 1.0), 1); // override alpha and boost edge colour with inversion of alpha
                OutputDepthTexture[texPixel] = topZ;
            }
            else
            {
                OutputColourTexture[texPixel] = float4(0, 0, 0, 0);
                OutputDepthTexture[texPixel] = 0;
            }
        }
        else // no depth write, no need to do alpha cutout
        {
            // no depth threshold, or don't care
            OutputColourTexture[texPixel] = float4(colourRGB, alpha); // with alpha
            OutputDepthTexture[texPixel] = topZ;
        }
        
    }
    else
    {
        OutputColourTexture[pix] = float4(0, 0, 0, 0);
        OutputDepthTexture[pix] = 0;
    }

}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void CSRenderViewDataNoGroupSharedMemory(uint3 groupID : SV_GroupID,
            uint3 threadIDInGroup : SV_GroupThreadID,
            uint3 dispatchThreadID : SV_DispatchThreadID)
{
    
    uint2 localPos = threadIDInGroup.xy;
    uint2 globalPos = uint2(
        groupID.x * TILE_SIZE + localPos.x,
        groupID.y * TILE_SIZE + localPos.y); // Or just use dispatchThreadID.xy
    
    // TODO: precompute
    uint W = (uint) VecScreenParams.x;
    uint H = (uint) VecScreenParams.y;
    uint horizontal_block_count = (W + TILE_SIZE - 1) / TILE_SIZE; // RoundUp(W / TileSize)
    
    uint2 pix = globalPos;
    if (pix.x >= OutputTextureSize.x || pix.y >= OutputTextureSize.y)
        return;
    
    float2 pixf = float2(pix.x, pix.y);
    uint pix_id = W * pix.y + pix.x;
    
    // out of bounds check
    bool inside = pix.x < W && pix.y < H;
    bool done = !inside;
    
    // Load start/end range of IDs to process in bit sorted list.
    uint flattenGroupId = groupID.y * horizontal_block_count + groupID.x;
    // Ranges.length = numTileX * numTileY = totalTileCount = totalGroupCount
    // .xy contains splatIdx. range.x = lower bound splatIdx(inclusive), range.y = upper bound splatIdx (exclusive)
    // fetch sorted splats index range     
    uint2 splatRange = TileToSplatRanges[flattenGroupId];
    uint splatIndexStart = splatRange.x;
    uint splatIndexEnd = splatRange.y; // exclusive
    int remainedSplats = splatIndexEnd - splatIndexStart;
    
    // Initialize helper variables
    float T = 1.0f;
    float3 C = float3(0, 0, 0);
    
    float topZ = 0;
    
    // Doing each batch, iterate over collectged splats
    for (int j = 0; !done && j < remainedSplats; j++)
    {
        uint tileConjSplatIdx = splatIndexStart + j;
        if (tileConjSplatIdx >= NumTileConjugateSplat)
            break;

        int splatIdx = GetSortedSplatViewIndex(tileConjSplatIdx);

        if (splatIdx >= SplatCount)
            continue;
            
        float2 mean = TheSplatViewData[splatIdx].mean_xy; // somehow need to access the splat to get mean
        float4 con_o = TheSplatViewData[splatIdx].conic;
        float alpha;
        bool alphaValid = CalcAlpha(con_o, mean, pixf, alpha);
            
        if (!alphaValid)
            continue;
            
        float test_T = T * (1 - alpha);
        if (test_T < 0.0001f)
        {
            done = true;
            continue;
        }
        
        topZ = max(topZ, clamp(TheSplatViewData[splatIdx].radii_clipz.y, 0.0, 1.0));
            
        // Eq. (3) from 3D Gaussian splatting paper.
        // features: calculated splat color buffer from previous stage
        C += TheSplatViewData[splatIdx].diffuse_opacity.rgb * alpha * T;
            
        T = test_T;
    }

    // All threads that treat valid pixel write out their final
	// rendering data to the frame and auxiliary buffers.
    if (inside)
    {
        float3 colourRGB = C;

        uint2 texPixel = uint2(pix.x, H - 1 - pix.y); // this will output image on the top left corner, easier for composite to sample

        
        float alpha = (1.0 - T);
        // sRGB is a gamma-encoded color space (approx gamma 2.2). To convert from linear to sRGB, Unreal applies a gamma correction, roughly
        // sRGB = pow(linear, 1/2.2)
        // So usually Unreal expect an input of linear colour so that the gamma correction to sRGB goes as it expected.
        // Our stuff is always in sRGB.
        // But depending on which stage to inject the image, you will need to either apply the inverse gamma correction UnrealSRGBToLinear(c), or leave it alone
        // So if it's after tone mapping(ToneMapping, FXAA), you should remove the term
        
            
        // Write to OutputDepthTexture based on clip space depth calculated in preprocess stage
        // Trick depth with alpha value to "soften" the edge usually won't do better
        if (DepthOutputThreshold.x > 0) // check if depth write is on
        {
            // do depth threshold
            if (alpha > DepthOutputThreshold.w)
            {
                OutputColourTexture[texPixel] = float4(colourRGB / alpha, 1.0); // override alpha and boost edge colour with inversion of alpha
                OutputDepthTexture[texPixel] = topZ;
            }
            else
            {
                OutputColourTexture[texPixel] = float4(0,0,0,0);
                OutputDepthTexture[texPixel] = 0;
            }
        }
        else // no depth write, no need to do alpha cutout
        {
            // no depth threshold, or don't care
            OutputColourTexture[texPixel] = float4(colourRGB, alpha); // with alpha
            OutputDepthTexture[texPixel] = topZ;
        }
        
    }
}

#else

// Dummy
[numthreads(1, 1, 1)]
void CSRenderViewDataNoGroupSharedMemory(uint3 groupID : SV_GroupID,
            uint3 threadIDInGroup : SV_GroupThreadID,
            uint3 dispatchThreadID : SV_DispatchThreadID)
{
}
#endif
