#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

// GaussianSplatData type
#include "GaussianSplatTypes.ush"
#include "GaussianSplatConstants.ush"
#include "GaussianSplatCommon.ush"


///////////////////////
// DATA FROM CPU
uint SplatCount;
/////////////////////

/////////////////////
// SORTING DATA
RWStructuredBuffer<uint> SortValueList_A;  // ordinal id, maps to VertexFactory's _InstanceIdToSortedId
/////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////
// GPU sorting initialisation, only for quad renderer
[numthreads(INIT_SORTING_THREADS, 1, 1)]
void CSInitSortData(uint3 DTid : SV_DispatchThreadID)
{
    uint idx = DTid.x;
    if (idx > SplatCount)
        return;

    // splat ordinal
    SortValueList_A[idx] = idx;
}
