#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

// GaussianSplatData type
#include "GaussianSplatTypes.ush"
#include "GaussianSplatConstants.ush"
#include "GaussianSplatCommon.ush"


///////////////////////
// DATA FROM CPU
uint SplatCount;
/////////////////////

/////////////////////
// SORTING DATA
RWBuffer<uint> SortValueList_A; // ordinal id, maps to VertexFactory's _InstanceIdToSortedId
/////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////
// GPU sorting initialisation, only for quad renderer
[numthreads(INIT_SORTING_THREADS, 1, 1)]
void CSInitSortData(uint3 DTid : SV_DispatchThreadID)
{
    uint idx = DTid.x;
    if (idx > SplatCount)
        return;

    // splat ordinal
    SortValueList_A[idx] = idx;
}


Buffer<uint> SortValueResult;
RWByteAddressBuffer SortValueFinal;

// Try using compute shader to copy Buffer<uint> -> ByteAddressBuffer for vetex factory to use
// because GPU sort doesn't like ByteAddressBuffer or StructuredBuffer<T>
// and Vertex Factory doesn't like Buffer<T>
// Silly but this is the only way I found working on Mac
[numthreads(COPY_SORTING_THREADS, 1, 1)]
void CSCopySortData(uint3 DTid : SV_DispatchThreadID)
{
    uint idx = DTid.x;
    if (idx > SplatCount)
        return;

    // Copy contents from SortValueResult ->SortValueFinal
    uint resultVal = SortValueResult[idx];
    SortValueFinal.Store(idx*4, resultVal);
}
