#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

#include "GaussianSplatConstants.ush"
#include "GaussianSplatTypes.ush"




// These are NOT getting a regular pixel based rectangle
// The rectangle.xy is based on horizontal and vertical tile index!

// TileSize = The pixel size each tile has horizontally and vertically
// TileCount = The total number of tiles horizontally and vertically
// Output TileIndexRangeMax is exclusive indices
void CalcTileIndexRange(const float2 p, int max_radius, out uint2 TileIndexRangeMin, out uint2 TileIndexRangeMax, uint2 TileSize, uint2 TileCount)
{
    TileIndexRangeMin = uint2(
        min(TileCount.x, max((int) 0, (int) ((p.x - max_radius) / TileSize.x))),
		min(TileCount.y, max((int) 0, (int) ((p.y - max_radius) / TileSize.y)))
	);

    TileIndexRangeMax = uint2(
        min(TileCount.x, max((int) 0, (int) ((p.x + max_radius + TileSize.x - 1) / TileSize.x))),
		min(TileCount.y, max((int) 0, (int) ((p.y + max_radius + TileSize.y - 1) / TileSize.y)))
	);
}


bool CalcAlpha(float4 con_o, float2 mean, uint2 pixf, out float alpha)
{
    // Resample using conic matrix (cf. "Surface 
	// Splatting" by Zwicker et al., 2001)
    float2 d = float2(mean.x - pixf.x, mean.y - pixf.y);
    float power = -0.5f * (con_o.x * d.x * d.x + con_o.z * d.y * d.y) - con_o.y * d.x * d.y;
    if (power > 0.0)
        return false;
    // Eq. (2) from 3D Gaussian splatting paper.
	// Obtain alpha by multiplying with Gaussian opacity
	// and its exponential falloff from mean.
	// Avoid numerical instabilities (see paper appendix). 
    alpha = min(0.99, con_o.w * exp(power));
    if (alpha < 1.0 / 255.0)
        return false;

    return true;
}