#ifndef GAUSSIAN_SPLATT_TYPES
#define GAUSSIAN_SPLATT_TYPES

#include "GaussianSplatConstants.ush"

struct EncodedSplatPosition
{
    uint x_bits;
    uint y_bits;
    uint z_bits;
};

struct EncodedSplat3DegreeSHCoeffs
{
    uint sh[15];
};

struct DecodedSplatData
{
    float4 pos;
    float4 col_a;
    float3 scale;
    float4 quat;
    float3 sh_coeffs[MAXIMUM_SH_COEFFS];
};

// NOTE: Change of structure will need to be done in EvercoastGaussianSplatCSResult.h too
struct SplatViewData
{
    float4 pos;             // local space
    float2 axis1, axis2;    // clip space axis
    float4 diffuse_opacity;
    float4 conic;
    int2   mean_xy;         // screen space mean
    float2 radii_clipz;     // my_radius, depth in clip space (repurposed to clip_pos.zw in offscreen quad renderer)
    uint   depth16;         // view space depth in 16bit float format, stored in lower 16 bits
    float3 clip_pos;        // position in clip space before perspective division
    int4   tile_idx_ranges; // covered tile index from xy(top left) to zw(bottom right)    
};

uint _NumSplats;


#endif //GAUSSIAN_SPLATT_TYPES